/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => VaultMindPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/settings.ts
var DEFAULT_SETTINGS = {
  apiKey: "",
  baseUrl: "https://api.deepseek.com/v1",
  model: "deepseek-chat",
  autoWrite: false,
  fieldPrefix: "vm_",
  enableBodyLinks: true,
  enableMoc: true,
  maxLinksPerNote: 3,
  mocFolderPath: "VaultMind/MOCs",
  tagAlignmentStrategy: "prefer_existing_and_autolink_moc"
};

// src/settingTab.ts
var import_obsidian = require("obsidian");
var VaultMindSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "VaultMind Settings" });
    new import_obsidian.Setting(containerEl).setName("DeepSeek API Key").setDesc("Your DeepSeek API key.").addText((text) => text.setPlaceholder("sk-...").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
      this.plugin.settings.apiKey = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Base URL").setDesc("API base URL for DeepSeek.").addText((text) => text.setPlaceholder("https://api.deepseek.com/v1").setValue(this.plugin.settings.baseUrl).onChange(async (value) => {
      this.plugin.settings.baseUrl = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Model").setDesc("Model name to use.").addText((text) => text.setPlaceholder("deepseek-chat").setValue(this.plugin.settings.model).onChange(async (value) => {
      this.plugin.settings.model = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Auto Write").setDesc("Automatically write metadata back to the file without confirmation.").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoWrite).onChange(async (value) => {
      this.plugin.settings.autoWrite = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Field Prefix").setDesc("Prefix for the metadata fields (default: vm_).").addText((text) => text.setPlaceholder("vm_").setValue(this.plugin.settings.fieldPrefix).onChange(async (value) => {
      this.plugin.settings.fieldPrefix = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Graph & Relations" });
    new import_obsidian.Setting(containerEl).setName("Enable Body Links").setDesc("Write [[wikilinks]] to the end of the note for Graph View.").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableBodyLinks).onChange(async (value) => {
      this.plugin.settings.enableBodyLinks = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Enable MOC").setDesc("Generate/Update Map of Content (MOC) pages.").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableMoc).onChange(async (value) => {
      this.plugin.settings.enableMoc = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Max Links Per Note").setDesc("Maximum number of related links to write to each note.").addSlider((slider) => slider.setLimits(1, 10, 1).setValue(this.plugin.settings.maxLinksPerNote).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.maxLinksPerNote = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("MOC Folder Path").setDesc("Folder where MOC pages will be stored.").addText((text) => text.setPlaceholder("VaultMind/MOCs").setValue(this.plugin.settings.mocFolderPath).onChange(async (value) => {
      this.plugin.settings.mocFolderPath = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Tag Alignment Strategy").setDesc("How to align new tags with existing MOCs/tags.").addDropdown((dropdown) => dropdown.addOption("off", "Off (No alignment)").addOption("prefer_existing", "Prefer Existing (Suggest existing tags)").addOption("prefer_existing_and_autolink_moc", "Prefer & Auto-link (Suggest and auto-bind to MOC)").setValue(this.plugin.settings.tagAlignmentStrategy).onChange(async (value) => {
      if (value === "off" || value === "prefer_existing" || value === "prefer_existing_and_autolink_moc") {
        this.plugin.settings.tagAlignmentStrategy = value;
        await this.plugin.saveSettings();
      }
    }));
  }
};

// src/commands.ts
var import_obsidian4 = require("obsidian");

// src/types.ts
var SourceType = /* @__PURE__ */ ((SourceType2) => {
  SourceType2["NOTE"] = "note";
  SourceType2["PAPER"] = "paper";
  SourceType2["EXCERPT"] = "excerpt";
  return SourceType2;
})(SourceType || {});

// src/detectors.ts
function detectSourceType(content, metadata) {
  if (metadata && metadata.vm_source_type) {
    if (Object.values(SourceType).includes(metadata.vm_source_type)) {
      return metadata.vm_source_type;
    }
  }
  const contentLower = content.toLowerCase();
  const paperKeywords = [/\babstract\b/, /\bkeywords\b/, /\breferences\b/, /\bintroduction\b/];
  if (paperKeywords.some((regex) => regex.test(contentLower))) {
    return "paper" /* PAPER */;
  }
  const excerptKeywords = [/\bexcerpt from\b/, /\bsource:\b/, /\bquoted from\b/];
  if (excerptKeywords.some((regex) => regex.test(contentLower))) {
    return "excerpt" /* EXCERPT */;
  }
  return "note" /* NOTE */;
}
function extractPaperMetadata(content) {
  const extracted = {};
  const abstractMatch = content.match(/#*\s*Abstract\s*\n+([\s\S]*?)(?=\n+#|\n+\w+\s*\n|$)/i);
  if (abstractMatch) {
    extracted.abstract = abstractMatch[1].trim();
  }
  const keywordsMatch = content.match(/#*\s*Keywords\s*:\s*(.*?)(?=\n|$)/i);
  if (keywordsMatch) {
    extracted.keywords = keywordsMatch[1].split(",").map((kw) => kw.trim());
  }
  return extracted;
}

// src/promptBuilder.ts
function buildNotePrompt(content, existingTags = []) {
  const tagContext = existingTags.length > 0 ? `
    \u76EE\u524D\u5DF2\u6709\u7684\u77E5\u8BC6\u4E3B\u9898(MOC)\u5305\u62EC: ${existingTags.join(", ")}\u3002\u5982\u679C\u5185\u5BB9\u5339\u914D\uFF0C\u8BF7\u4F18\u5148\u4ECE\u8FD9\u4E9B\u4E3B\u9898\u4E2D\u9009\u62E9\u4F5C\u4E3A\u6807\u7B7E\u3002` : "";
  return `
    \u4F60\u662F\u4E00\u4E2A\u4E13\u4E1A\u7684\u77E5\u8BC6\u7BA1\u7406\u52A9\u624B\u3002\u8BF7\u5206\u6790\u4EE5\u4E0B\u7B14\u8BB0\u5185\u5BB9\uFF0C\u5E76\u63D0\u4F9B\u6458\u8981\u3001\u6807\u7B7E\u548C\u5173\u8054\u5EFA\u8BAE\u3002${tagContext}
    
    \u5185\u5BB9:
    ${content}
    
    \u8BF7\u4EE5 JSON \u683C\u5F0F\u63D0\u4F9B\u8F93\u51FA\uFF0C\u7ED3\u6784\u5982\u4E0B\uFF1A
    {
      "vm_summary": "3-5 \u53E5\u7684\u7B14\u8BB0\u6838\u5FC3\u6458\u8981\uFF08\u7B80\u4F53\u4E2D\u6587\uFF09\u3002",
      "vm_content_tags": ["\u6807\u7B7E1", "\u6807\u7B7E2"],
      "vm_file_tags": ["\u77E5\u8BC6\u70B9", "\u601D\u8003", "\u95EE\u9898", \u6216 "\u6458\u5F55"],
      "vm_related_notes": ["\u5EFA\u8BAE\u7684\u76F8\u5173\u4E3B\u98981", "\u5EFA\u8BAE\u7684\u76F8\u5173\u4E3B\u98982"]
    }
    \u6CE8\u610F\uFF08\u5B66\u672F\u6807\u7B7E\u89C4\u8303\uFF09\uFF1A
    1. \u6240\u6709\u5185\u5BB9\u5FC5\u987B\u4F7F\u7528\u7B80\u4F53\u4E2D\u6587\u3002
    2. vm_content_tags \u5FC5\u987B\u662F\u5B66\u672F\u5E38\u7528\u6982\u5FF5\u6216\u4E13\u4E1A\u672F\u8BED\uFF0C\u80FD\u5728\u6807\u9898\u6216\u6458\u8981\u4E2D\u627E\u5230\u8BED\u4E49\u4F9D\u636E\u3002
    3. \u6807\u7B7E\u5FC5\u987B\u77ED\u3001\u7A33\u5B9A\u3001\u53EF\u590D\u7528\uFF0C\u4F18\u5148\u8F93\u51FA 1-3 \u4E2A\u3002\u7981\u6B62\u751F\u9020\u4E3A\u4E86\u5F53\u524D\u6587\u6863\u4E34\u65F6\u62DF\u5408\u7684\u6807\u7B7E\u3002
    4. \u907F\u514D\u4F7F\u7528\u8FC7\u6CDB\u7684\u8BCD\uFF0C\u5982\u201C\u7814\u7A76\u201D\u201C\u5B66\u4E60\u201D\u201C\u65B9\u6CD5\u201D\u8FD9\u7C7B\u7A7A\u6CDB\u6807\u7B7E\u3002
    5. \u5982\u679C\u5185\u5BB9\u65E0\u6CD5\u786E\u5B9A\u9AD8\u8D28\u91CF\u5B66\u672F\u6807\u7B7E\uFF0C\u8BF7\u8F93\u51FA\u7A7A\u6570\u7EC4 []\u3002
    6. vm_file_tags \u5FC5\u987B\u4ECE\u63D0\u4F9B\u7684\u9009\u9879\u4E2D\u9009\u62E9\u3002
    `;
}
function buildPaperPrompt(content, extracted, existingTags = []) {
  const abstract = extracted.abstract || "\u672A\u627E\u5230\u3002";
  const keywords = extracted.keywords ? extracted.keywords.join(", ") : "\u672A\u627E\u5230\u3002";
  const tagContext = existingTags.length > 0 ? `
    \u76EE\u524D\u5DF2\u6709\u7684\u77E5\u8BC6\u4E3B\u9898(MOC)\u5305\u62EC: ${existingTags.join(", ")}\u3002\u5982\u679C\u5185\u5BB9\u5339\u914D\uFF0C\u8BF7\u4F18\u5148\u4ECE\u8FD9\u4E9B\u4E3B\u9898\u4E2D\u9009\u62E9\u4F5C\u4E3A\u6807\u7B7E\u3002` : "";
  return `
    \u4F60\u662F\u4E00\u4E2A\u4E13\u4E1A\u7684\u5B66\u672F\u52A9\u624B\u3002\u8BF7\u5206\u6790\u4EE5\u4E0B\u8BBA\u6587\u5185\u5BB9\uFF0C\u5E76\u63D0\u4F9B\u6458\u8981\u3001\u6807\u7B7E\u548C\u5173\u8054\u5EFA\u8BAE\u3002${tagContext}
    
    \u8BBA\u6587\u5185\u5BB9:
    ${content}
    
    \u63D0\u53D6\u7684\u6458\u8981:
    ${abstract}
    
    \u63D0\u53D6\u7684\u5173\u952E\u8BCD:
    ${keywords}
    
    \u8BF7\u4EE5 JSON \u683C\u5F0F\u63D0\u4F9B\u8F93\u51FA\uFF0C\u7ED3\u6784\u5982\u4E0B\uFF1A
    {
      "vm_summary": "3-5 \u53E5\u7684\u8BBA\u6587\u6838\u5FC3\u6458\u8981\uFF08\u7B80\u4F53\u4E2D\u6587\uFF09\u3002\u4F18\u5148\u53C2\u8003\u63D0\u53D6\u7684\u6458\u8981\u3002",
      "vm_content_tags": ["\u5173\u952E\u8BCD1", "\u5173\u952E\u8BCD2"],
      "vm_file_tags": ["\u8BBA\u6587"],
      "vm_related_notes": ["\u5EFA\u8BAE\u7684\u76F8\u5173\u4E3B\u98981", "\u5EFA\u8BAE\u7684\u76F8\u5173\u4E3B\u98982"]
    }
    \u6CE8\u610F\uFF08\u5B66\u672F\u6807\u7B7E\u89C4\u8303\uFF09\uFF1A
    1. \u6240\u6709\u5185\u5BB9\u5FC5\u987B\u4F7F\u7528\u7B80\u4F53\u4E2D\u6587\u3002
    2. vm_content_tags \u4F18\u5148\u5BF9\u9F50\u539F\u6587\u5173\u952E\u8BCD\uFF0C\u4F46\u5FC5\u987B\u8F6C\u6362\u4E3A\u6807\u51C6\u5B66\u672F\u672F\u8BED\u3002
    3. \u6807\u7B7E\u5FC5\u987B\u77ED\u3001\u7A33\u5B9A\u3001\u53EF\u590D\u7528\uFF0C\u4F18\u5148\u8F93\u51FA 1-3 \u4E2A\u3002\u7981\u6B62\u751F\u9020\u62DF\u5408\u6807\u7B7E\u3002
    4. \u907F\u514D\u4F7F\u7528\u8FC7\u6CDB\u7684\u8BCD\uFF0C\u5982\u201C\u7814\u7A76\u201D\u201C\u5206\u6790\u201D\u7B49\u3002
    `;
}
function buildExcerptPrompt(content, existingTags = []) {
  const tagContext = existingTags.length > 0 ? `
    \u76EE\u524D\u5DF2\u6709\u7684\u77E5\u8BC6\u4E3B\u9898(MOC)\u5305\u62EC: ${existingTags.join(", ")}\u3002\u5982\u679C\u5185\u5BB9\u5339\u914D\uFF0C\u8BF7\u4F18\u5148\u4ECE\u8FD9\u4E9B\u4E3B\u9898\u4E2D\u9009\u62E9\u4F5C\u4E3A\u6807\u7B7E\u3002` : "";
  return `
    \u4F60\u662F\u4E00\u4E2A\u4E13\u4E1A\u7684\u77E5\u8BC6\u7BA1\u7406\u52A9\u624B\u3002\u8BF7\u5206\u6790\u4EE5\u4E0B\u6458\u5F55\u5185\u5BB9\uFF0C\u5E76\u63D0\u4F9B\u6458\u8981\u3001\u6807\u7B7E\u548C\u5173\u8054\u5EFA\u8BAE\u3002${tagContext}
    
    \u6458\u5F55\u5185\u5BB9:
    ${content}
    
    \u8BF7\u4EE5 JSON \u683C\u5F0F\u63D0\u4F9B\u8F93\u51FA\uFF0C\u7ED3\u6784\u5982\u4E0B\uFF1A
    {
      "vm_summary": "3-5 \u53E5\u7684\u6458\u5F55\u6838\u5FC3\u6458\u8981\uFF08\u7B80\u4F53\u4E2D\u6587\uFF09\u3002\u5F3A\u8C03\u8FD9\u662F\u4E00\u4E2A\u6458\u5F55\u3002",
      "vm_content_tags": ["\u6807\u7B7E1", "\u6807\u7B7E2"],
      "vm_file_tags": ["\u6458\u5F55"],
      "vm_related_notes": ["\u5EFA\u8BAE\u7684\u76F8\u5173\u4E3B\u98981", "\u5EFA\u8BAE\u7684\u76F8\u5173\u4E3B\u98982"]
    }
    \u6CE8\u610F\uFF08\u5B66\u672F\u6807\u7B7E\u89C4\u8303\uFF09\uFF1A
    1. \u6240\u6709\u5185\u5BB9\u5FC5\u987B\u4F7F\u7528\u7B80\u4F53\u4E2D\u6587\u3002
    2. vm_content_tags \u5FC5\u987B\u662F\u6807\u51C6\u5B66\u672F\u6216\u4E13\u4E1A\u6982\u5FF5\uFF0C\u4FDD\u6301\u7CBE\u7B80\uFF081-3 \u4E2A\uFF09\u3002\u7981\u6B62\u751F\u9020\u6807\u7B7E\u3002
    3. \u4F18\u5148\u8F93\u51FA\u53EF\u590D\u7528\u7684\u6838\u5FC3\u672F\u8BED\u3002
    `;
}

// src/deepseekClient.ts
var import_obsidian2 = require("obsidian");
async function callDeepSeek(prompt, settings) {
  const { apiKey, baseUrl, model } = settings;
  if (!apiKey) {
    throw new Error("DeepSeek API Key is not set.");
  }
  const url = `${baseUrl.replace(/\/$/, "")}/chat/completions`;
  const payload = {
    model,
    messages: [
      { role: "system", content: "You are a helpful assistant that outputs JSON only." },
      { role: "user", content: prompt }
    ],
    response_format: { type: "json_object" }
  };
  const response = await (0, import_obsidian2.requestUrl)({
    url,
    method: "POST",
    headers: {
      "Authorization": `Bearer ${apiKey}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify(payload)
  });
  if (response.status !== 200) {
    throw new Error(`DeepSeek API error: ${response.status} ${response.text}`);
  }
  const result = response.json;
  const content = result.choices[0].message.content;
  return JSON.parse(content);
}

// src/frontmatterService.ts
async function writeMetadataToFrontmatter(app, file, metadata, plugin) {
  const prefix = plugin.settings.fieldPrefix || "vm_";
  await app.fileManager.processFrontMatter(file, (fm) => {
    fm[`${prefix}summary`] = metadata.vm_summary;
    fm[`${prefix}content_tags`] = metadata.vm_content_tags;
    fm[`${prefix}file_tags`] = metadata.vm_file_tags;
    fm[`${prefix}source_type`] = metadata.vm_source_type;
    fm[`${prefix}status`] = "processed";
    fm[`${prefix}processed_at`] = metadata.vm_processed_at;
    if (metadata.vm_related_notes) {
      fm[`${prefix}related_notes`] = metadata.vm_related_notes;
    }
    if (metadata.vm_suggested_folder) {
      fm[`${prefix}suggested_folder`] = metadata.vm_suggested_folder;
      fm[`${prefix}folder_status`] = metadata.vm_folder_status;
      fm[`${prefix}folder_confidence`] = metadata.vm_folder_confidence;
      fm[`${prefix}folder_reason`] = metadata.vm_folder_reason;
    }
  });
}

// src/linkWriter.ts
async function writeBodyLinks(app, file, relatedNotes, plugin) {
  if (!plugin.settings.enableBodyLinks || relatedNotes.length === 0)
    return;
  const content = await app.vault.read(file);
  const sectionTitle = "## \u76F8\u5173\u7B14\u8BB0";
  const maxLinks = plugin.settings.maxLinksPerNote || 3;
  const linksToWrite = relatedNotes.slice(0, maxLinks).map((note) => `- [[${note}]]`).join("\n");
  const newSection = `

${sectionTitle}
${linksToWrite}
`;
  const sectionRegex = new RegExp(`${sectionTitle}[\\s\\S]*?(?=\\n#|$)`, "g");
  let newContent;
  if (sectionRegex.test(content)) {
    newContent = content.replace(sectionRegex, `${sectionTitle}
${linksToWrite}`);
  } else {
    newContent = content.trimEnd() + newSection;
  }
  await app.vault.modify(file, newContent);
}

// src/mocService.ts
var import_obsidian3 = require("obsidian");
async function updateMocPage(app, topic, noteTitle, plugin) {
  if (!plugin.settings.enableMoc || !topic)
    return;
  const mocFolder = plugin.settings.mocFolderPath || "VaultMind/MOCs";
  const mocPath = `${mocFolder}/${topic}.md`;
  await ensureFolderExists(app, mocFolder);
  let mocFile = app.vault.getAbstractFileByPath(mocPath);
  let content = "";
  if (mocFile instanceof import_obsidian3.TFile) {
    content = await app.vault.read(mocFile);
  } else {
    content = `# ${topic}

## \u76F8\u5173\u7B14\u8BB0
`;
  }
  const link = `- [[${noteTitle}]]`;
  if (!content.includes(`[[${noteTitle}]]`)) {
    const sectionTitle = "## \u76F8\u5173\u7B14\u8BB0";
    if (content.includes(sectionTitle)) {
      content = content.replace(sectionTitle, `${sectionTitle}
${link}`);
    } else {
      content += `
${sectionTitle}
${link}
`;
    }
    if (mocFile instanceof import_obsidian3.TFile) {
      await app.vault.modify(mocFile, content);
    } else {
      await app.vault.create(mocPath, content);
    }
  }
}
async function ensureFolderExists(app, path) {
  const parts = path.split("/");
  let currentPath = "";
  for (const part of parts) {
    currentPath += (currentPath ? "/" : "") + part;
    const folder = app.vault.getAbstractFileByPath(currentPath);
    if (!folder) {
      await app.vault.createFolder(currentPath);
    }
  }
}

// src/commands.ts
async function getExistingMocs(app, plugin) {
  const mocFolder = plugin.settings.mocFolderPath || "VaultMind/MOCs";
  const folder = app.vault.getAbstractFileByPath(mocFolder);
  if (folder instanceof import_obsidian4.TFolder) {
    return folder.children.filter((file) => file instanceof import_obsidian4.TFile && file.extension === "md").map((file) => file.name.replace(/\.md$/, ""));
  }
  return [];
}
async function analyzeCurrentNote(app, plugin) {
  const activeView = app.workspace.getActiveViewOfType(import_obsidian4.MarkdownView);
  if (!activeView) {
    new import_obsidian4.Notice("No active markdown note found.");
    return null;
  }
  const file = activeView.file;
  if (!file)
    return null;
  return analyzeFile(app, plugin, file);
}
async function analyzeFolder(app, plugin, folder) {
  const files = app.vault.getMarkdownFiles().filter((file) => folder.path ? file.path.startsWith(`${folder.path}/`) : true);
  if (files.length === 0) {
    new import_obsidian4.Notice("VaultMind: No markdown files found in the current folder.");
    return;
  }
  const prefix = plugin.settings.fieldPrefix || "vm_";
  const records = [];
  let processedCount = 0;
  let skippedCount = 0;
  new import_obsidian4.Notice(`VaultMind: Starting batch analysis (Phase 1: Tagging) of ${files.length} files...`);
  for (const file of files) {
    const cache = app.metadataCache.getFileCache(file);
    const frontmatter = (cache == null ? void 0 : cache.frontmatter) || {};
    const status = frontmatter[`${prefix}status`];
    if (status === "processed") {
      const existing = readRecordFromFrontmatter(file, frontmatter, prefix);
      if (existing) {
        records.push(existing);
      }
      skippedCount++;
      continue;
    }
    const metadata = await analyzeFile(app, plugin, file);
    if (metadata) {
      const suggestion = computeFolderSuggestion(metadata, records, plugin);
      metadata.vm_suggested_folder = suggestion.folder;
      metadata.vm_folder_status = suggestion.status;
      metadata.vm_folder_confidence = suggestion.confidence;
      metadata.vm_folder_reason = suggestion.reason;
      await writeMetadataToFrontmatter(app, file, metadata, plugin);
      records.push({ file, metadata });
      processedCount++;
      await sleep(400);
    }
  }
  new import_obsidian4.Notice(`VaultMind: Phase 1 complete. Processed: ${processedCount}, Skipped: ${skippedCount}`);
  if (records.length === 0) {
    new import_obsidian4.Notice("VaultMind: No records available for linking.");
    return;
  }
  new import_obsidian4.Notice("VaultMind: Starting Phase 2 (Linking)...");
  const linkCount = await applyGraphRelations(app, plugin, records, prefix);
  new import_obsidian4.Notice(`VaultMind: Phase 2 complete. Links updated for ${linkCount} files.`);
}
async function analyzeFile(app, plugin, file) {
  var _a;
  const content = await app.vault.read(file);
  const metadata = ((_a = app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter) || {};
  const sourceType = detectSourceType(content, metadata);
  let existingMocs = [];
  if (plugin.settings.tagAlignmentStrategy !== "off") {
    existingMocs = await getExistingMocs(app, plugin);
  }
  let prompt = "";
  if (sourceType === "paper" /* PAPER */) {
    const extracted = extractPaperMetadata(content);
    prompt = buildPaperPrompt(content, extracted, existingMocs);
  } else if (sourceType === "excerpt" /* EXCERPT */) {
    prompt = buildExcerptPrompt(content, existingMocs);
  } else {
    prompt = buildNotePrompt(content, existingMocs);
  }
  new import_obsidian4.Notice(`Analyzing ${file.name} with DeepSeek...`);
  try {
    const llmResult = await callDeepSeek(prompt, plugin.settings);
    const validatedMetadata = {
      vm_summary: llmResult.vm_summary || "No summary provided.",
      vm_content_tags: validateTags(llmResult.vm_content_tags || []),
      vm_file_tags: llmResult.vm_file_tags || [],
      vm_source_type: sourceType,
      vm_status: "draft",
      vm_processed_at: new Date().toISOString(),
      vm_related_notes: llmResult.vm_related_notes || []
    };
    return validatedMetadata;
  } catch (error) {
    new import_obsidian4.Notice(`Error analyzing ${file.name}: ${error.message}`);
    console.error(error);
    return null;
  }
}
function validateTags(tags) {
  const forbiddenWords = ["\u7814\u7A76", "\u5B66\u4E60", "\u65B9\u6CD5", "\u5206\u6790", "\u7B14\u8BB0", "\u601D\u8003", "\u95EE\u9898"];
  return tags.map((tag) => tag.trim()).filter((tag) => tag.length >= 2 && tag.length <= 15).filter((tag) => !forbiddenWords.includes(tag)).slice(0, 3);
}
async function applyGraphRelations(app, plugin, records, prefix) {
  let linkCount = 0;
  const existingMocs = await getExistingMocs(app, plugin);
  for (const record of records) {
    const relatedNotes = computeRelatedNotes(record, records, plugin.settings.maxLinksPerNote || 3);
    let primaryTopic = "";
    const contentTags = record.metadata.vm_content_tags;
    if (plugin.settings.tagAlignmentStrategy === "prefer_existing_and_autolink_moc") {
      const matchedTag = contentTags.find((tag) => existingMocs.includes(tag));
      if (matchedTag) {
        primaryTopic = matchedTag;
      }
    } else if (plugin.settings.tagAlignmentStrategy === "prefer_existing") {
      const matchedTag = contentTags.find((tag) => existingMocs.includes(tag));
      if (matchedTag) {
        primaryTopic = matchedTag;
      }
    } else {
      primaryTopic = contentTags[0] || "";
    }
    if (relatedNotes.length === 0 && !primaryTopic) {
      continue;
    }
    await app.fileManager.processFrontMatter(record.file, (fm) => {
      fm[`${prefix}related_notes`] = relatedNotes;
      fm[`${prefix}graph_links_written`] = relatedNotes.length > 0;
      if (primaryTopic) {
        const shouldWriteMocPage = plugin.settings.tagAlignmentStrategy === "prefer_existing_and_autolink_moc" || plugin.settings.tagAlignmentStrategy !== "off" && existingMocs.includes(primaryTopic);
        if (shouldWriteMocPage) {
          const existingMocPages = normalizeArray(fm[`${prefix}moc_pages`]);
          if (!existingMocPages.includes(primaryTopic)) {
            fm[`${prefix}moc_pages`] = [...existingMocPages, primaryTopic];
          }
        }
      }
    });
    if (relatedNotes.length > 0) {
      await writeBodyLinks(app, record.file, relatedNotes, plugin);
    }
    if (primaryTopic && plugin.settings.enableMoc) {
      const shouldUpdateMocFile = plugin.settings.tagAlignmentStrategy === "prefer_existing_and_autolink_moc" || plugin.settings.tagAlignmentStrategy !== "off" && existingMocs.includes(primaryTopic);
      if (shouldUpdateMocFile) {
        await updateMocPage(app, primaryTopic, record.file.basename, plugin);
      }
    }
    linkCount++;
    await sleep(200);
  }
  return linkCount;
}
function computeRelatedNotes(current, allRecords, maxLinks) {
  const scored = allRecords.filter((record) => record.file.path !== current.file.path).map((record) => {
    var _a, _b;
    const score = computeOverlapScore(current.metadata, record.metadata);
    return {
      title: record.file.basename,
      score,
      sameFolder: ((_a = current.file.parent) == null ? void 0 : _a.path) === ((_b = record.file.parent) == null ? void 0 : _b.path)
    };
  }).map((item) => ({
    ...item,
    score: item.score > 0 ? item.score : item.sameFolder ? 1 : 0
  })).filter((item) => item.score > 0).sort((a, b) => b.score - a.score || a.title.localeCompare(b.title));
  const related = [];
  for (const item of scored) {
    if (!related.includes(item.title)) {
      related.push(item.title);
    }
    if (related.length >= maxLinks) {
      break;
    }
  }
  return related;
}
function computeOverlapScore(left, right) {
  const leftTags = /* @__PURE__ */ new Set([...left.vm_content_tags, ...left.vm_file_tags]);
  const rightTags = /* @__PURE__ */ new Set([...right.vm_content_tags, ...right.vm_file_tags]);
  let score = 0;
  for (const tag of leftTags) {
    if (rightTags.has(tag)) {
      score += 2;
    }
  }
  return score;
}
function readRecordFromFrontmatter(file, frontmatter, prefix) {
  const contentTags = normalizeArray(frontmatter == null ? void 0 : frontmatter[`${prefix}content_tags`]);
  const fileTags = normalizeArray(frontmatter == null ? void 0 : frontmatter[`${prefix}file_tags`]);
  const sourceType = (frontmatter == null ? void 0 : frontmatter[`${prefix}source_type`]) || "note" /* NOTE */;
  if (contentTags.length === 0 && fileTags.length === 0) {
    return null;
  }
  return {
    file,
    metadata: {
      vm_summary: String((frontmatter == null ? void 0 : frontmatter[`${prefix}summary`]) || ""),
      vm_content_tags: contentTags,
      vm_file_tags: fileTags,
      vm_source_type: sourceType,
      vm_status: String((frontmatter == null ? void 0 : frontmatter[`${prefix}status`]) || "processed"),
      vm_processed_at: String((frontmatter == null ? void 0 : frontmatter[`${prefix}processed_at`]) || new Date().toISOString()),
      vm_related_notes: normalizeArray(frontmatter == null ? void 0 : frontmatter[`${prefix}related_notes`])
    }
  };
}
function normalizeArray(value) {
  if (Array.isArray(value)) {
    return value.map((item) => String(item).trim()).filter(Boolean);
  }
  if (typeof value === "string") {
    return value.split(",").map((item) => item.trim()).filter(Boolean);
  }
  return [];
}
function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
function computeFolderSuggestion(current, allRecords, plugin) {
  var _a;
  const folderScores = {};
  const folderCounts = {};
  for (const record of allRecords) {
    const folderPath = ((_a = record.file.parent) == null ? void 0 : _a.path) || "";
    if (!folderPath || folderPath === "/")
      continue;
    const score = computeOverlapScore(current, record.metadata);
    folderScores[folderPath] = (folderScores[folderPath] || 0) + score;
    folderCounts[folderPath] = (folderCounts[folderPath] || 0) + 1;
  }
  let bestFolder = "";
  let maxScore = -1;
  for (const folder in folderScores) {
    const avgScore = folderScores[folder] / folderCounts[folder];
    if (avgScore > maxScore) {
      maxScore = avgScore;
      bestFolder = folder;
    }
  }
  if (bestFolder && maxScore >= 2) {
    return {
      folder: bestFolder,
      status: "matched",
      confidence: maxScore >= 4 ? "high" : "medium",
      reason: `\u4E0E\u8BE5\u6587\u4EF6\u5939\u4E0B\u6587\u6863\u6807\u7B7E\u91CD\u53E0\u5EA6\u9AD8 (\u5E73\u5747\u5206: ${maxScore.toFixed(1)})`
    };
  }
  const primaryTag = current.vm_content_tags[0] || current.vm_file_tags[0] || "\u672A\u5206\u7C7B";
  const suggestedNew = `VaultMind/${primaryTag}`;
  return {
    folder: suggestedNew,
    status: "suggested_new",
    confidence: "low",
    reason: "\u672A\u627E\u5230\u5339\u914D\u7684\u73B0\u6709\u6587\u4EF6\u5939\uFF0C\u6839\u636E\u4E3B\u6807\u7B7E\u5EFA\u8BAE\u65B0\u76EE\u5F55"
  };
}

// src/previewModal.ts
var import_obsidian5 = require("obsidian");
var PreviewModal = class extends import_obsidian5.Modal {
  constructor(app, file, metadata, plugin, onConfirm) {
    super(app);
    this.file = file;
    this.metadata = metadata;
    this.plugin = plugin;
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "VaultMind Analysis Preview" });
    contentEl.createEl("p", { text: "Review the generated metadata before writing it to the note." });
    const previewContainer = contentEl.createDiv({ cls: "vaultmind-preview-container" });
    this.createPreviewRow(previewContainer, "Summary", this.metadata.vm_summary);
    this.createPreviewRow(previewContainer, "Content Tags", this.metadata.vm_content_tags.join(", "));
    this.createPreviewRow(previewContainer, "File Tags", this.metadata.vm_file_tags.join(", "));
    this.createPreviewRow(previewContainer, "Source Type", this.metadata.vm_source_type);
    if (this.metadata.vm_related_notes && this.metadata.vm_related_notes.length > 0) {
      this.createPreviewRow(previewContainer, "Related Notes", this.metadata.vm_related_notes.join(", "));
    }
    if (this.metadata.vm_suggested_folder) {
      this.createPreviewRow(previewContainer, "Suggested Folder", `${this.metadata.vm_suggested_folder} (${this.metadata.vm_folder_status})`);
      this.createPreviewRow(previewContainer, "Folder Confidence", this.metadata.vm_folder_confidence || "low");
    }
    new import_obsidian5.Setting(contentEl).addButton((btn) => btn.setButtonText("Cancel").onClick(() => {
      this.close();
    })).addButton((btn) => btn.setButtonText("Apply to Note").setCta().onClick(async () => {
      await writeMetadataToFrontmatter(this.app, this.file, this.metadata, this.plugin);
      this.onConfirm();
      this.close();
    }));
  }
  createPreviewRow(parent, label, value) {
    const row = parent.createDiv({ cls: "vaultmind-preview-row" });
    row.createEl("strong", { text: `${label}: ` });
    row.createEl("span", { text: value });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// main.ts
var VaultMindPlugin = class extends import_obsidian6.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new VaultMindSettingTab(this.app, this));
    this.addCommand({
      id: "analyze-current-note",
      name: "Analyze current note",
      callback: async () => {
        const metadata = await analyzeCurrentNote(this.app, this);
        if (metadata) {
          const activeView = this.app.workspace.getActiveViewOfType(import_obsidian6.MarkdownView);
          if (activeView && activeView.file) {
            if (this.settings.autoWrite) {
              await writeMetadataToFrontmatter(this.app, activeView.file, metadata, this);
              new import_obsidian6.Notice("VaultMind: Metadata updated automatically.");
            } else {
              new PreviewModal(this.app, activeView.file, metadata, this, () => {
                new import_obsidian6.Notice("VaultMind: Metadata updated.");
              }).open();
            }
          }
        }
      }
    });
    this.addCommand({
      id: "analyze-folder",
      name: "Analyze notes in current folder",
      callback: async () => {
        const activeView = this.app.workspace.getActiveViewOfType(import_obsidian6.MarkdownView);
        if (!activeView || !activeView.file || !activeView.file.parent) {
          new import_obsidian6.Notice("No active folder found.");
          return;
        }
        const folder = activeView.file.parent;
        if (folder instanceof import_obsidian6.TFolder) {
          await analyzeFolder(this.app, this, folder);
        }
      }
    });
    console.log("loading VaultMind plugin");
  }
  async onunload() {
    console.log("unloading VaultMind plugin");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
